spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/mbti?characterEncoding=UTF-8&serverTimezone=UTC
#    jdbc:h2:tcp://localhost/~/mbti
    username : root
    password :
    driver-class-name : com.mysql.cj.jdbc.Driver
#    org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        format_sql : true
